### ISSUE TITLE
 Error in qTox repositories for Fedora 24 !

### ISSUE THREAD

**Issue by Nokia808** [abbat/tox.pkg#3]
I'm on Fedora 24 X64 bit. I added repository for qTox from following site:
https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox
by entering in my terminal following:
dnf config-manager --add-repo http://download.opensuse.org/repositories/home:antonbatenev:tox/Fedora_24/home:antonbatenev:tox.repo

Then I installed qTox. I launched it, then it connected & I got ID & add someone & chat with him O.K

Latter on I discover that my package manager show me individual packages of qTox NOT INSTALLED, including the core package: tox-libtoxcore !! How this ? tox-libtoxcore is vital without it qTox not work !!

Please look for attached screenshoots (all of them taken after installation of qTox)
![1](https://cloud.githubusercontent.com/assets/25375330/22795002/fc640aa8-eeec-11e6-830e-80e0fa4c5ca8.png)
![2](https://cloud.githubusercontent.com/assets/25375330/22795034/1e39279e-eeed-11e6-911e-a20521cd1968.png)
![3](https://cloud.githubusercontent.com/assets/25375330/22795365/5c6ddd60-eeee-11e6-9274-bbd2a2b6a6bd.png)
![4](https://cloud.githubusercontent.com/assets/25375330/22795381/68068dfc-eeee-11e6-9322-e742da0ec220.png)

**Comment by abbat** [comment]
qTox linked statically with tox-libtoxcore. tox-libtoxcore need only when compiling qTox yourself.
