### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zetok** [abbat/tox.pkg#4]
Without specified/provided license all the stuff in this repo is proprietary – I think that this is not intended?

**Comment by abbat** [comment]
License for each package is the same as packaged project license (see */debian/copyright).

**Comment by zetok** [comment]
Ok, but those packages don't include all the files that are in this repo, right?

Packages are generated based on the scripts in this repo, and the scripts aren't included in the packages?

**Comment by abbat** [comment]
Non-package files (such as build scripts not included into package) you can use under Public Domain.

**Comment by zetok** [comment]
Putting something in public domain by author is possible only in some jurisdictions, so in jurisdictions that don't allow it the files would be proprietary.

For the same effect there is license `CC0`, which puts the work in public domain in jurisdictions that allow for it, and in those that don't allow it, there are provided permissions equivalent to public domain.

https://creativecommons.org/share-your-work/public-domain/cc0/

Btw, just mentioning that in the issue is not enough, this should be written at least in the README.md; something like

```
Files that are not covered by other licenses are under CC0 license: https://creativecommons.org/publicdomain/zero/1.0/legalcode
```

**Comment by abbat** [comment]
Would you create PR?

**Comment by zetok** [comment]
Feel free to apply the diff if it looks good:

```diff
diff --git a/README.md b/README.md
index 3dde893..6fc59f9 100644
--- a/README.md
+++ b/README.md
@@ -51,3 +51,12 @@ Click on interesting package name, follow "Download package" link, choose your d
 ### Feedback
 
 If you find some package useful, please email me which distro and package name(s) you are using.
+
+### License
+
+License of files in each `debian` directory is located in the `copyright` file
+under the respective `debian` directory.
+
+Files not covered by other licenses are licensed under the **CC0** license.
+
+[![CC0](https://licensebuttons.net/p/zero/1.0/88x31.png)](https://creativecommons.org/publicdomain/zero/1.0/)

```
