### ISSUE TITLE
Core Dumped on qTox

### ISSUE THREAD

**Issue by victorhck** [abbat/tox.pkg#5]
Hello.

I use qTox on openSUSE Tumbleweed. Since many weeks when I try to start qTox and put my password, nothing happens.
I run qTox from CLI and after prompted the password, I get the message
"Core Dumped" and nothing happens.

 $ qtox 
[18:40:02.325 UTC] persistence/settings.cpp:137 : Debug: "Loading settings from /home/victorhck/.config/tox/qtox.ini"
[18:40:02.440 UTC] widget/translator.cpp:56 : Debug: Loaded translation "es"
[18:40:02.440 UTC] widget/translator.cpp:65 : Debug: System translation loaded "es"
[18:40:02.441 UTC] ipc.cpp:59 : Debug: Our global IPC ID is  12253228710072289768
[18:40:02.489 UTC] ipc.cpp:77 : Debug: Attaching to the global shared memory
[18:40:02.505 UTC] ipc.cpp:279 : Debug: Previous owner timed out, taking ownership 5396012343253582726 -> 12253228710072289768
[18:40:02.505 UTC] main.cpp:215 : Debug: built on:  12:00:00 May  5 2017 ( 1495900694 )
[18:40:02.505 UTC] main.cpp:216 : Debug: commit:  5648106b34fc7dc3ad4e169651a0cbbd0139170a 

[18:40:02.505 UTC] nexus.cpp:85 : Debug: Starting up
[18:40:08.204 UTC] persistence/profile.cpp:117 : Debug: Loading tox save  "/home/victorhck/.config/tox/victorhck.tox"
Instrucción ilegal (core dumped)

I have this:
qTox, version: 5648106b34fc7dc3ad4e169651a0cbbd0139170a
Built: 12:00:00 May  5 2017

Any hint about this?
Thanks in advance.

**Comment by abbat** [comment]
Would you provide CPU info? Also try to install *-debuginfo package and get backtrace using gdb like this:

```
$ gdb --args /usr/bin/qtox
(gdb) run
... /* wait for core dumped */
(gdb) bt
```

**Comment by victorhck** [comment]
Thanks!
Don't know if I did it well. Here you have:
http://susepaste.org/47883432

**Comment by abbat** [comment]
```
$ cat /proc/cpuinfo
```
Seems your processor does not support extensions, which [required system libsodium](https://build.opensuse.org/build/openSUSE:Factory/standard/x86_64/libsodium/_log) (AVX for example).

**Comment by victorhck** [comment]
~~~~
victorhck@Geeko:~> cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Pentium(R) CPU B960 @ 2.20GHz
stepping        : 7
microcode       : 0x29
cpu MHz         : 1068.579
cache size      : 2048 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave lahf_lm epb xsaveopt dtherm arat pln pts
bugs            :
bogomips        : 4390.22
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Pentium(R) CPU B960 @ 2.20GHz
stepping        : 7
microcode       : 0x29
cpu MHz         : 1061.328
cache size      : 2048 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave lahf_lm epb xsaveopt dtherm arat pln pts
bugs            :
bogomips        : 4391.23
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
~~~~

**Comment by abbat** [comment]
Can you try to get sources of system libsodium and rebuild it for your CPU (and replace)?

**Comment by victorhck** [comment]
I download libsodium from their site, and compiled.
Also uninstalled the installed version from the repos.
After that updated the Tumbleweed system because new updates where available (qTox was one of them)
After reboot everything seems to works fine qith qTox. I checked that libsodium from repos where installed again!
Don't know exactly what happened!
Thanks a lot for your support and package for openSUSE.
